### ISSUE TITLE
Decide on a GraphQL Query Library

### ISSUE THREAD

**Issue by sanathkr** [RareCamp/RareCamp#18]
Choices:
- Apollo client
- React Query
- Amplify Lib DataStore
- Others?

**Comment by pipesorter** [comment]
@sanathkr  

### Apollo

In v3.0 it had useQuery, useMutation, I was excited to use custom hooks instead of using HOCs. Then hit a snag and bugs coz of these issues.

- https://github.com/apollographql/apollo-client/issues/6502 needed to do pagination, they did some weird change from their earlier implementation, it was not so good experience. 
- when implementing `refetch` had an issue https://github.com/apollographql/react-apollo/issues/3709 

I liked the earlier apollo versions, it was stable and usable, 3.0 with hooks though was good to start with, it started to break.

### React query or useSSR

I used `react-query` along with API.grapqhl (aws-amplify), I like it a lot, we won't need a global store like redux, if the store is going to just store data from backend, this solves it elegantly. I also have used `react-query` with a rest API, it has been a good experience. Had issues in understanding its configuration (it was making unnecessary fetch on browser tab focus, apparently had to disable), once understood, it is quite good.

### Datasore of aws-amplify

I just started to use this library, not sure how it refetches, paginates etc, haven't gone to the advanced part. I like the fact it abstracts and we could write something like `Datastore.save` and it translates into corresponding graphql query just like an ORM reminds of ActiveRecord ORM (ruby). 
https://docs.amplify.aws/lib/datastore/data-access/q/platform/js

Possible cons:
- This lib would probably work only with appsync (that uses @model) backend not with any graphql backend unlike the react-query or apollo approach. 
-

**Comment by sanathkr** [comment]
So the other day we decided to stick with `react-query` right? Any cons?

**Comment by pipesorter** [comment]
No bro, we didn't decide on a library or approach, you wanted me to list the pros and cons for each approach, hence this issue. 

There are no cons to `react-query` as a standalone lib, just that it doesn't have model concept as `Datastore` and each graphql query has to be explicitly define, probably we will have a folder full of explicitly defined queries instead of a model that abstracts them.  @sanathkr 

Then we can continue with `react-query` with `API.graphql` of `aws-amplify`? @sanathkr  @ianvonholt @bboure

**Comment by bboure** [comment]
I personally have had a good experience with apollo-client and hooks (small disclaimer: with react-native). I have only used that one so far so I can't really opinate on the others:

Hooks are great and easy to use in Apollo. I have not experienced issues like @pipesorter. What I like about Apollo is the auto-rerender of all my (affected) components any time the cache is updated (i.e.: by a mutation). (Not sure how the other libraries handle that). It supports caching, using the ID field from the GraphQl model. There is no need for a global store (redux) either.

About Amplify, I have no experience, but as I already mentioned somewhere else, it works great with AppSync and Cognito out-of-the-box. It also supports offline (for mobile it is great), but it should not be a deal-breaker here. 

> each graphql query has to be explicitly define, probably we will have a folder full of explicitly defined queries instead of a model that abstracts them

I am not sure how the datastore works on Amplify (or elsewhere). Having explicit queries/mutations is probably not a bad thing IMHO when you think in terms of GraphQL and one of its basic principles: Avoid over-fetching.

**Comment by brettstack** [comment]
@pipesorter and I made the decision on the call - react-query https://react-query.tanstack.com/ + Amplify's Api.graphql https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js
