### ISSUE TITLE
Task Details

### ISSUE THREAD

**Issue by brettstack** [RareCamp/RareCamp#32]
- [ ] Edit title
- [ ] Edit description
- [ ] WYSIWIG editor for details
- [ ] Should details Markdown be rendered by default and user clicks Edit to show WYSIWYG?
- [ ] Tests

Not required for MVP:

- [ ] About knock-in mouse
- [ ] Service providers
- [ ] Upload files
- [ ] Edit Status, Owner, Budget, Start/End Date since these are editable via Project view

**Comment by sanathkr** [comment]
- Unless you have experience with other editors, I would highly recommend https://quilljs.com/ for rich text editor. It's highly customizable.
- I would recommend storing rich text as JSON in the backend instead of Markdown, if possible. Markdowns can store HTML in them which would be problematic when people copy/paste text from elsewhere.
- @brettstack Add an optional task for sanitizing the JSON data from rich text editor. It could contain incompatible fonts which should be stripped out.
